[package]
name = "yams-api"
description = "API for the YAMS project"
version.workspace = true
authors.workspace = true
license-file.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
yams-core = { path = "../yams-core" }

thiserror = { workspace = true }
error-stack = { workspace = true }

async-trait = { workspace = true }

uuid = { workspace = true }
chrono = { workspace = true }
http = { workspace = true }
rust_decimal = { workspace = true }

poem-openapi = { workspace = true, features = ["uuid", "chrono", "rust_decimal"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[features]
default = ["serde", "openapi"]
openapi = ["dep:poem-openapi"]
serde = ["dep:serde", "uuid/serde", "chrono/serde", "error-stack/serde", "rust_decimal/serde"]

[dev-dependencies]
pollster = { version = "0.4.0", features = ["macro"] }
yams-fakes = { path = "../yams-fakes" }

[[bin]]
name = "export_spec"
required-features = ["openapi"]

