[package]
name = "yams-core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }

async-trait = { workspace = true }
fxhash = { workspace = true }

chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
rust_decimal = { workspace = true, features = ["serde"] }

[dev-dependencies]
pollster = { version = "0.4.0", features = ["macro"] }

