[package]
name = "yams-api"
version = "0.1.0"
authors = ["Tim Peko <timererd@gmail.com>"]
description = "API for the YAMS project"
license-file = "../../LICENSE"
edition = "2024"

[dependencies]
yams-core = { path = "../core" }

async-trait = { workspace = true }

thiserror = { workspace = true }
error-stack = { workspace = true }

uuid = { workspace = true }
chrono = { workspace = true }

poem-openapi = { workspace = true, features = ["uuid", "chrono"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[features]
default = ["serde", "openapi"]
openapi = ["dep:poem-openapi"]
serde = ["dep:serde", "uuid/serde", "chrono/serde", "error-stack/serde"]

[[bin]]
name = "export_spec"
required-features = ["openapi"]

