[workspace]
members = [
    "crates/*",
    "backend/server",
    "frontend/src-tauri",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Tim Peko <timerertim@gmail.com>", "David Rathmair", "Dominik Wernsdorfer", "Julian Bachinger", "David Edthaler", "Daniel Ferihumer"]
license-file = "../../LICENSE"
edition = "2024"
repository = "https://github.com/HTBLA-Grieskirchen/YAMS/"

[workspace.dependencies]
thiserror = "2.0.20"
error-stack = { version = "0.8.0", default-features = false, features = ["std"] }
bon = { version   = "3.9.3" }
async-trait = "0.1.92"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.21.0", features = ["v4", "serde"] }
clap = { version = "4.5.59", features = ["derive", "env"] }
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1.0", features = ["serde"] }
rustc-hash = "2.1.0"
libsql = { version = "0.9.29", default-features = false, features = ["serde", "core"] }
poem = "3.0"
poem-openapi = { version = "5.1.16", features = ["swagger-ui", "uuid", "redoc"] }
http = "1.5.0"

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true
