["fix:fmt"]
description = "Format all the code"
depends = ["fmt:*"]

["fix:lint"]
description = "Apply all lint suggestions"
depends = ["lint:?* --fix"]

["fix"]
description = "Fix all the code, ensure all guidelines"
run = [
    {task = "fix:lint"},
    {task = "fix:fmt"}
]
