#:schema https://mise.jdx.dev/schema/mise-task.json

["fmt:biome"]
description = "Format the frontend code with biome"
dir = "{{ vars.REPO_ROOT }}/frontend"
usage = """
flag "--check" env="YAMS_FMT_CHECK" help="Only performs a check of the formatting"
"""
run = """
#!/usr/bin/env bash
if [ "${usage_check:-}" = "true" ]; then
  npm run check:format
else
  npm run fix:format
fi
"""

["fmt:rust"]
description = "Format the rust code"
usage = """
flag "--check" env="YAMS_FMT_CHECK" help="Only performs a check of the formatting"
"""
run = """
#!/usr/bin/env bash
FMT_CMD=$([ "${usage_check:-}" = "true" ] && echo "--check")
cargo fmt --all $FMT_CMD
"""

["fmt:typst"]
description = "Format the typst code"
usage = """
flag "--check" env="YAMS_FMT_CHECK" help="Only performs a check of the formatting"
"""
tools = { typstyle = "latest" }
run = """
#!/usr/bin/env bash
typstyle . --wrap-text $([ "${usage_check:-}" = "true" ] && echo "--diff" || echo "-i")
"""
