export {
  useBehandlungErstellenMutation,
  useHaustierErstellenMutation,
  useKlientErstellenMutation,
  useLeistungAusBehandlungBuchenMutation,
  useLeistungAusProduktBuchenMutation,
  useLeistungManuellErfassenMutation,
  useProduktErstellenMutation,
  useSeminarBuchungAnlegenMutation,
  useSeminarBuchungStornierenMutation,
  useSeminarErstellenMutation,
  useSeminarTerminAbgehaltenMutation,
  useSeminarTerminAbsagenMutation,
  useSeminarTerminAktualisierenMutation,
  useSeminarTerminPlanenMutation,
  useTagesabschlussDurchführenMutation,
} from "./mutations";
export {
  useAlleBehandlungenQuery,
  useAlleHaustiereQuery,
  useAlleKlientenQuery,
  useAlleLeistungenQuery,
  useAlleProdukteQuery,
  useAlleRechnungenQuery,
  useAlleSeminareQuery,
  useAlleSeminarTermineQuery,
  useHaustierByIdQuery,
  useHealthQuery,
  useRechnungenFürKlientQuery,
  useSeminarByIdQuery,
  useSeminarTerminByIdQuery,
  useSeminarUmsatzPrognoseQuery,
  useSeminarUmsatzVorschauQuery,
} from "./queries";
export { useYamsApiReady } from "./use-yams-api-ready";
