[package]
name = "yams-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
error-stack = { workspace = true }
tracing = { workspace = true }

async-trait = { workspace = true }
rustc-hash = { workspace = true }
bon = { workspace = true }
futures = { workspace = true }

chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
rust_decimal = { workspace = true, features = ["serde"] }

[dev-dependencies]
pollster = { version = "0.4.0", features = ["macro"] }
yams-fakes = { path = "../yams-fakes" }
test-log = { workspace = true }
tracing-subscriber = { workspace = true }

