[package]
name = "yams-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
yams-core = { path = "../../crates/yams-core" }
yams-persistence = { path = "../../crates/yams-persistence" }
yams-api = { path = "../../crates/yams-api" }
yams-filesystemstore = { path = "../../crates/yams-filesystemstore" }
yams-typstreports = { path = "../../crates/yams-typstreports" }

thiserror = { workspace = true }
error-stack = { workspace = true }

async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = { workspace = true }

uuid = { workspace = true, features = ["v4", "serde"] }

poem = { workspace = true, features = ["compression", "requestid"] }
poem-openapi = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }
tracing-subscriber = { workspace = true }
