import type {NextPage} from 'next'
import Head from 'next/head'
import MyApp from "./_app";
import {StoreProvider} from "../stores";

const Home: NextPage = () => {
  return (
      <div className="">
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app"/>
              <link rel="icon" href="/favicon.ico"/>
          </Head>

          <main className="">
              <StoreProvider>
                  <MyApp/>
              </StoreProvider>
          </main>
      </div>
  )
}

export default Home
