import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import MyApp from "./_app";

const Home: NextPage = () => {
  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/frontend/yams/src/public/favicon.ico"/>
        </Head>

        <main className={styles.main}>
            <MyApp/>
        </main>
      </div>
  )
}

export default Home
