[package]
name = "yams"
version = "0.1.0"
description = "A management software for patients and animals"
authors = ["Tim Peko", "David Rathmair", "Dominik Wernsdorfer", "Julian Bachinger", "David Edthaler", "Daniel Ferihumer"]
license-file = "../../LICENSE"
repository = "https://github.com/HTBLA-Grieskirchen/YAMS/"
default-run = "yams"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "^2.0", features = [] }

[dependencies]
yams-core = { path = "../../backend/core" }
yams-persistence = { path = "../../backend/persistence" }
yams-api = { path = "../../backend/api", default-features = false, features = ["serde"] }

serde = { workspace = true }
serde_json = { workspace = true }

tauri = { version = "2.10.2", features = [] }
tauri-plugin-shell = "2.3.5"
tauri-plugin-fs = "2.0"
url = { version = "^2.3.1", features = ["serde"] }
directories = "6.0.0"

