name: "Integration Test"
on:
  # Triggers the workflow on pull request events but only for default branches
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to run this workflow from another workflow
  workflow_call:

jobs:
  smoke-test:
    name: "Integration tests on all platforms"
    strategy:
      matrix:
        platform: [ ubuntu-20.04 ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "frontend/src-tauri"
          cache-on-failure: true

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install npm dependencies
        working-directory: frontend
        run: npm install

        # Here should be integration tests but setup is complicated and therefore priority set to low
      - name: Test web build
        working-directory: frontend
        run: npm run test

      - name: Build web application
        working-directory: frontend
        run: npm run build && npm run export

      - name: Test web build
        working-directory: frontend
        run: npm run test

      - name: Test backend code
        working-directory: frontend
        run: cargo test

      - name: Build tauri application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
