name: "Unit Test"
on:
  # Triggers the workflow on pull request events but only for default and protected branches
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to run this workflow from another workflow
  workflow_call:

jobs:
  test-build:
    name: "Unit test on all platforms"
    strategy:
      matrix:
        platform: [ ubuntu-20.04, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "frontend/src-tauri"
          cache-on-failure: true

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install npm dependencies
        working-directory: frontend
        run: npm install

      - name: Build web application
        working-directory: frontend
        run: npm run build && npm run export

      - name: Test web build
        working-directory: frontend
        run: npm run test

      - name: Test backend code
        working-directory: frontend/src-tauri
        run: cargo test

      - name: Build tauri application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
